# Numpy Practice

In [1]:
import numpy as np

###  Basics

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
npArray = np.array(mylist) #Creating np array
npArray

array([1, 2, 3])

In [4]:
type(npArray)

numpy.ndarray

In [5]:
mylist = [[1,2,3],[3,4,5], [7,8,9]]

In [6]:
mylist

[[1, 2, 3], [3, 4, 5], [7, 8, 9]]

In [7]:
matrix = np.array(mylist)

In [8]:
matrix

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [9]:
matrix.shape

(3, 3)

In [10]:
np.arange(0, 10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [81]:
np.zeros((4,8)) #4 rows, 8 columns

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,5)) + 6 # 1+6 in 5x5 matrix

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [14]:
(np.ones(5) +5) / 100

array([0.06, 0.06, 0.06, 0.06, 0.06])

In [15]:
np.linspace(0,10,20) #Quite different from np.arange (evenly spaced number)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Numpy Random

In [17]:
np.random.rand(5,5) #Random

array([[0.50826482, 0.99759453, 0.15746279, 0.14263866, 0.77727877],
       [0.21086468, 0.90555065, 0.75718963, 0.20985858, 0.78052857],
       [0.77728032, 0.32692469, 0.56447302, 0.39886658, 0.06391957],
       [0.11324305, 0.41330263, 0.79941652, 0.39430263, 0.73468654],
       [0.26491691, 0.97571782, 0.40160604, 0.91191189, 0.0276961 ]])

In [18]:
np.random.randn(10)

array([ 0.47139026,  0.1187066 ,  1.27374835, -2.33131738,  1.67019389,
        2.03828127, -1.44204408, -0.49434527,  0.64958346,  0.69068626])

In [19]:
np.random.normal(1,2,5)

array([ 1.5039387 ,  1.32010388,  2.64326876,  3.65560882, -0.36342561])

In [20]:
np.random.randint(1,100,(5,5))

array([[70, 83, 12, 53, 76],
       [54, 68, 20,  2, 85],
       [10, 61, 28, 91, 65],
       [72, 28,  2, 85, 94],
       [11, 63, 41, 59, 84]])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
randArr = np.random.randint(0, 50, 25)

In [23]:
randArr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,  1, 23, 43, 29, 37,  1,
       20, 32, 11, 21, 43, 24, 48, 26])

In [24]:
reshapeArr = randArr.reshape(5,5) #transforming 1D matrix to 5x5D matrix
reshapeArr

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2],
       [21,  1, 23, 43, 29],
       [37,  1, 20, 32, 11],
       [21, 43, 24, 48, 26]])

In [25]:
reshapeArr.max()

48

In [26]:
reshapeArr.min()

1

In [27]:
reshapeArr.mean()

24.0

In [28]:
reshapeArr.argmax() #Index of the max value

23

In [29]:
reshapeArr.dtype #Data type

dtype('int32')

## Numpy Indexing

In [30]:
arr = np.arange(0,25,2)

In [31]:
arr[:] #same as py list

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [32]:
arr[5:] #same as py list

array([10, 12, 14, 16, 18, 20, 22, 24])

In [33]:
arr[:5] #same as py list

array([0, 2, 4, 6, 8])

In [34]:
arr / 5

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8])

In [35]:
arr + .6

array([ 0.6,  2.6,  4.6,  6.6,  8.6, 10.6, 12.6, 14.6, 16.6, 18.6, 20.6,
       22.6, 24.6])

In [36]:
arr**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400, 484, 576],
      dtype=int32)

In [37]:
slice_arr = arr[0:5]

In [38]:
slice_arr[:]

array([0, 2, 4, 6, 8])

In [39]:
slice_arr[:] = 100

In [40]:
slice_arr[:]

array([100, 100, 100, 100, 100])

In [41]:
arr[:] #shallow copy effect

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24])

In [42]:
arr_cpy = arr.copy() #deep copy

In [43]:
arr_cpy[:] = 99

In [44]:
arr_cpy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [45]:
arr[:] #no effect bcz of deep copy

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24])

### *Indexing on a 2D array* 

In [46]:
arr_2d = np.arange(0,24,1).reshape(4,6)

In [47]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
arr_2d.shape

(4, 6)

In [49]:
arr_2d[2,2] #same as py list

14

In [50]:
arr_2d[:,1]

array([ 1,  7, 13, 19])

In [51]:
arr_2d[2, 3:]

array([15, 16, 17])

In [52]:
arr_2d[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### ***Conditional Selection***

In [53]:
arr = np.arange(1,11)

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr>4 #conditional selection

In [57]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
arr[bool_arr] #Filtering 

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[arr>4] #same thing in short/one step

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[arr<= 5]

array([1, 2, 3, 4, 5])

## Numpy Operations

In [61]:
ara = np.arange(1,23,3)

In [62]:
ara


array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [63]:
ara + ara

array([ 2,  8, 14, 20, 26, 32, 38, 44])

In [64]:
(ara + 4 ) / 2

array([ 2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. ])

In [65]:
ara ** 2

array([  1,  16,  49, 100, 169, 256, 361, 484], dtype=int32)

In [66]:
1/ara

array([1.        , 0.25      , 0.14285714, 0.1       , 0.07692308,
       0.0625    , 0.05263158, 0.04545455])

In [67]:
ara/0

<ipython-input-67-4729f868b91c>:1: RuntimeWarning: divide by zero encountered in true_divide
  ara/0


array([inf, inf, inf, inf, inf, inf, inf, inf])

In [68]:
ara/ara

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
ara.dot(ara)

1436

In [70]:
np.sqrt(ara)

array([1.        , 2.        , 2.64575131, 3.16227766, 3.60555128,
       4.        , 4.35889894, 4.69041576])

In [71]:
np.log(ara)

array([0.        , 1.38629436, 1.94591015, 2.30258509, 2.56494936,
       2.77258872, 2.94443898, 3.09104245])

In [72]:
np.tan(ara)

array([1.55740772, 1.15782128, 0.87144798, 0.64836083, 0.46302113,
       0.30063224, 0.15158947, 0.00885166])

In [73]:
ara.min()

1

In [74]:
ara.max()

22

In [75]:
ara.mean()

11.5

In [76]:
ara_2d = ara.reshape(2,4)

In [77]:
ara_2d

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22]])

In [78]:
ara_2d.sum()

92

In [79]:
ara_2d.sum(axis= 0) #sum across the rows
#Produces sum of the columns

array([14, 20, 26, 32])

In [80]:
ara_2d.sum(axis=1)
#Produces sum of the rows

array([22, 70])

## Exercise Question