<a href="https://colab.research.google.com/github/RifatIslamOmio/Python-ML-library-practice/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
arr = np.arange(1,13)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr.dtype

dtype('int64')

## **Creating Tensor From Numpy**

In [5]:
tarr = torch.from_numpy(arr)

In [6]:
tarr.dtype

torch.int64

In [7]:
#another way to create tensor
torch.as_tensor(arr)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr = arr.reshape(3,4)

In [9]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
tarr = torch.from_numpy(arr)

In [11]:
tarr

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [12]:
arr[0][0] = 99

In [13]:
tarr

tensor([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [14]:
arr = np.arange(0.0, 5, .25).reshape(4,5)

In [15]:
arr


array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [1.25, 1.5 , 1.75, 2.  , 2.25],
       [2.5 , 2.75, 3.  , 3.25, 3.5 ],
       [3.75, 4.  , 4.25, 4.5 , 4.75]])

In [16]:
my_tensor = torch.tensor(arr)

In [17]:
my_tensor

tensor([[0.0000, 0.2500, 0.5000, 0.7500, 1.0000],
        [1.2500, 1.5000, 1.7500, 2.0000, 2.2500],
        [2.5000, 2.7500, 3.0000, 3.2500, 3.5000],
        [3.7500, 4.0000, 4.2500, 4.5000, 4.7500]], dtype=torch.float64)

In [18]:
other_tensor = torch.from_numpy(arr)

In [19]:
arr[0][0] = 0.99 #Change to test

In [20]:
other_tensor #value will be changed in tensor as well

tensor([[0.9900, 0.2500, 0.5000, 0.7500, 1.0000],
        [1.2500, 1.5000, 1.7500, 2.0000, 2.2500],
        [2.5000, 2.7500, 3.0000, 3.2500, 3.5000],
        [3.7500, 4.0000, 4.2500, 4.5000, 4.7500]], dtype=torch.float64)

In [21]:
my_tensor #value wont change (creates it's own reference)

tensor([[0.0000, 0.2500, 0.5000, 0.7500, 1.0000],
        [1.2500, 1.5000, 1.7500, 2.0000, 2.2500],
        [2.5000, 2.7500, 3.0000, 3.2500, 3.5000],
        [3.7500, 4.0000, 4.2500, 4.5000, 4.7500]], dtype=torch.float64)

## **Part 2**
### Creating torch from scratch

In [22]:
my_tensor = torch.empty(2,2)

In [23]:
my_tensor

tensor([[2.1757e-05, 3.0918e-41],
        [3.3631e-44, 0.0000e+00]])

In [24]:
torch.zeros(4,4, dtype=torch.float64) #Can mention the data type you want

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [25]:
torch.ones(5,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
x = torch.arange(0,25,3).reshape(3,3) #same as numpy

In [27]:
x

tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])

In [28]:
torch.linspace(0,18,12)   #linearly spaced data

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [29]:
#change data type
my_tensor = torch.tensor([1,2,3,4,5])

In [30]:
my_tensor.dtype

torch.int64

In [31]:
my_tensor = my_tensor.type(torch.float64)

In [32]:
my_tensor

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

### Random

In [33]:
torch.rand(4,5)

tensor([[0.4335, 0.8987, 0.7579, 0.8060, 0.0702],
        [0.1564, 0.5891, 0.0618, 0.0908, 0.2789],
        [0.3482, 0.7165, 0.8782, 0.7954, 0.6246],
        [0.0086, 0.8374, 0.3960, 0.7826, 0.9805]])

In [34]:
torch.randn(4,5)

tensor([[ 0.5512,  0.4132, -0.1571, -1.1292,  1.4150],
        [-0.2135,  1.0596,  0.8710, -0.9920,  1.9823],
        [ 0.1743, -0.5325,  0.4799, -0.9521,  2.9620],
        [-0.3941, -0.8972,  0.3083,  2.4228,  0.6956]])

In [35]:
torch.randint(0,15,(4,5))

tensor([[13, 10,  1,  0, 14],
        [ 4,  3,  2,  4,  0],
        [ 0,  2,  2, 10, 14],
        [12, 13,  9, 11,  7]])

In [36]:
x = torch.zeros(2,5)

In [37]:
torch.rand_like(x)

tensor([[0.1719, 0.2106, 0.2744, 0.3203, 0.9361],
        [0.4469, 0.4328, 0.4299, 0.3392, 0.1399]])

In [38]:
torch.randint_like(x, 0, 15)

tensor([[ 4.,  3.,  5.,  2.,  8.],
        [ 8., 12.,  7.,  8., 14.]])

In [39]:
torch.randn_like(x,dtype=torch.float64)

tensor([[-1.2862, -0.2061, -0.6868, -0.6856,  0.3940],
        [ 0.6633, -1.4127,  0.4212, -2.0981,  1.4950]], dtype=torch.float64)

In [40]:
torch.manual_seed(23)
torch.rand(4,3)

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100],
        [0.2933, 0.9205, 0.5876],
        [0.1299, 0.6729, 0.1028]])

## **Tensor** **Operations**

In [41]:
x = torch.arange(6).reshape(3,2)


In [42]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [43]:
x[1,1]

tensor(3)

In [44]:
x[:, 0]

tensor([0, 2, 4])

In [45]:
x[:]

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [46]:
x[:,1:] #slicing for column

tensor([[1],
        [3],
        [5]])

In [47]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
x.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [49]:
x = torch.arange(10)

In [50]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#Finding out the second dimention
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
x.view(-1,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

## Torch Operations

In [53]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [54]:
a+b

tensor([5., 7., 9.])

In [55]:
a = a.add_(b)
#a = a.add(b)
#a = a+b

In [56]:
a

tensor([5., 7., 9.])

In [57]:
a.mul_(b)

tensor([20., 35., 54.])

In [58]:
a

tensor([20., 35., 54.])

In [59]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [60]:
a*b

tensor([ 4., 10., 18.])

In [61]:
a.dot(b)

tensor(32.)

In [62]:
b = torch.tensor([4.,5.,6.])
b = b.reshape(3,1)
a = a.reshape(1,3)

In [63]:
torch.mm(a,b) #Matrix multiplication

tensor([[32.]])

In [64]:
a @ b #do the same

tensor([[32.]])

In [65]:
torch.norm(a) # |a|

tensor(3.7417)

In [66]:
b.norm()

tensor(8.7750)

In [67]:
a.numel() #number of elements

3